---
output: html_document
---

Make box plots for between replicates.

Make a CAT plot for the top differences between GM12878 and K562 H3K27ac

```{r}
library(data.table)
library(Matrix)
library(dplyr)
library(dcon)
library(GenomicRanges)
library(strawr)

```

```{r}
myfiles <- list.files(pattern = 'gm12878_5000_results_gamma0.5_chr.*rds')
results_cohesin <- NULL
n <- 0
for (f in myfiles) {
  d <- readRDS(f)
  chr <- unlist(strsplit(unlist(strsplit(f,'_'))[5],'\\.'))[1]
  r <- d@results$df
  r$chrom <- chr
  if (is.null(results_cohesin)) {
    results_cohesin <- r
  } else {
    results_cohesin <- bind_rows(results_cohesin, r)
  }
}
```


```{r}
myfiles <- list.files(pattern = 'k562_ctcf_2500_results_sum_gamma0.5_chr.*rds')
results_mnase <- NULL
n <- 0
for (f in myfiles) {
  d <- readRDS(f)
  chr <- unlist(strsplit(unlist(strsplit(f,'_'))[7],'\\.'))[1]
  r <- d@results$df
  r$chrom <- chr
  if (is.null(results_mnase)) {
    results_mnase <- r
  } else {
    results_mnase <- bind_rows(results_mnase, r)
  }
}
```


```{r}
myfiles <- list.files(pattern = 'h3k27ac_results_gamma0.5_chr.*rds')
results_h3k27ac <- NULL
n <- 0
for (f in myfiles) {
  d <- readRDS(f)
  chr <- unlist(strsplit(unlist(strsplit(f,'_'))[4],'\\.'))[1]
  r <- d@results$df
  r$chrom <- chr
  if (is.null(results_h3k27ac)) {
    results_h3k27ac <- r
  } else {
    results_h3k27ac <- bind_rows(results_h3k27ac, r)
  }
}
results_h3k27ac <- results_h3k27ac %>%
  filter((grepl('gm12878',m1)&grepl('gm12878',m2)) | (grepl('k562',m1)&grepl('k562',m2))) %>%
  mutate(sample = case_when(
    grepl('gm12878',m1) ~ 'GM12878\nH3K27ac\nMboI',
    grepl('k562',m1) ~ 'K562\nH3K27ac\nMboI'
  ))
```

```{r}
myfiles <- list.files(pattern = 'lps_2500_results_g0.5_chr.*rds')
results_lps <- NULL
n <- 0
for (f in myfiles) {
  d <- readRDS(f)
  chr <- unlist(strsplit(unlist(strsplit(f,'_'))[4],'\\.'))[1]
  r <- d@results$df
  r$chrom <- chr
  if (is.null(results_lps)) {
    results_lps <- r
  } else {
    results_lps <- bind_rows(results_lps, r)
  }
}
results_lps <- results_lps %>%
  filter((grepl('141',m1)&grepl('141',m2)) | (grepl('853',m1)&grepl('853',m2))) %>%
  mutate(sample = case_when(
    grepl('141',m1) ~ 'LPS141\nH3K27ac\nMboI',
    grepl('853',m1) ~ 'LPS853\nH3K27ac\nMboI'
  ))
```


# Boxplot


```{r}
results_cohesin %>%
  mutate(sample = 'GM12878\nCohesin (RAD21) \nMboI') %>%
  bind_rows(results_mnase %>% mutate(sample = 'K562\nCTCF\nMNase')) %>%
  bind_rows(results_h3k27ac) %>%
  bind_rows(results_lps) %>%
  mutate(label = factor(label, levels = c('before','after'))) %>%
  ggplot(aes(x = sample, y= diff)) +
  geom_boxplot(aes(fill=label),outlier.shape = NA) +
  scale_fill_tableau(name = '', breaks = c('before', 'after'), labels = c('Before', 'After')) +
  theme_classic() +
  coord_cartesian(ylim=c(0,300)) +
  ylab('Difference between replicates') +
  xlab('')
ggsave('between-replicate-agreement-boxplots.pdf', height=3, width=6.5)
```



# Concordance at the top (CAT)



```{r}
myfiles <- list.files(pattern = 'h3k27ac_results_gamma0.5_chr.*rds')
results_h3k27ac <- NULL
n <- 0
for (f in myfiles) {
  d <- readRDS(f)
  chr <- unlist(strsplit(unlist(strsplit(f,'_'))[4],'\\.'))[1]
  r <- d@results$df
  r$chrom <- chr
  if (is.null(results_h3k27ac)) {
    results_h3k27ac <- r
  } else {
    results_h3k27ac <- bind_rows(results_h3k27ac, r)
  }
}
results_h3k27ac <- results_h3k27ac %>%
  filter((grepl('gm12878',m1)&grepl('k562',m2)) | (grepl('k562',m1)&grepl('gm12878',m2)))
```

```{r}
myfiles <- list.files(pattern = 'lps_2500_results_g0.5_chr.*rds')
results_lps <- NULL
n <- 0
for (f in myfiles) {
  d <- readRDS(f)
  chr <- unlist(strsplit(unlist(strsplit(f,'_'))[5],'\\.'))[1]
  r <- d@results$df
  r$chrom <- chr
  if (is.null(results_lps)) {
    results_lps <- r
  } else {
    results_lps <- bind_rows(results_lps, r)
  }
}
results_lps <- results_lps %>%
  filter((grepl('141',m1)&grepl('853',m2)) | (grepl('853',m1)&grepl('141',m2)))
```



```{r}
THRESHES <- c(1,5,10,50, 100, 250, 500, 750, 1000, 2500, 5000, 7500, 1e4, 25000, 50000, 75000, 1e5)
cat_res <- data.frame(threshold = THRESHES, concordance = NA)
for (i in seq_along(THRESHES)) {
  before_loops <- results_h3k27ac %>%
    filter(m1=='gm12878_1', m2=='k562_1') %>%
    pivot_wider(names_from = label, values_from = diff) %>%
    filter(!is.na(after)) %>%
    mutate(id = paste(chrom,loop)) %>%
    arrange(desc(before)) %>%
    slice(1:THRESHES[i]) %>%
    pull(id) %>%
    unique()
  after_loops <- results_h3k27ac %>%
    filter(m1=='gm12878_1', m2=='k562_1') %>%
    pivot_wider(names_from = label, values_from = diff) %>%
    filter(!is.na(after)) %>%
    mutate(id = paste(chrom,loop)) %>%
    arrange(desc(after)) %>%
    slice(1:THRESHES[i]) %>%
    pull(id) %>%
    unique()
  cat_res$concordance[i] <- sum(before_loops %in% after_loops)/length(before_loops)
}
cat_res$samples <- 'GM12878_1 & K562_1'
final_res <- cat_res
cat_res <- data.frame(threshold = THRESHES, concordance = NA)
for (i in seq_along(THRESHES)) {
  before_loops <- results_h3k27ac %>%
    filter(m1=='gm12878_2', m2=='k562_2') %>%
    pivot_wider(names_from = label, values_from = diff) %>%
    filter(!is.na(after)) %>%
    mutate(id = paste(chrom,loop)) %>%
    arrange(desc(before)) %>%
    slice(1:THRESHES[i]) %>%
    pull(id) %>%
    unique()
  after_loops <- results_h3k27ac %>%
    filter(m1=='gm12878_2', m2=='k562_2') %>%
    pivot_wider(names_from = label, values_from = diff) %>%
    filter(!is.na(after)) %>%
    mutate(id = paste(chrom,loop)) %>%
    arrange(desc(after)) %>%
    slice(1:THRESHES[i]) %>%
    pull(id) %>%
    unique()
  cat_res$concordance[i] <- sum(before_loops %in% after_loops)/length(before_loops)
}
cat_res$samples <- 'GM12878_2 & K562_2'
final_res <- bind_rows(final_res,cat_res)
cat_res <- data.frame(threshold = THRESHES, concordance = NA)
for (i in seq_along(THRESHES)) {
  before_loops <- results_lps %>%
    filter(m1=='lps141_1', m2=='lps853_1') %>%
    pivot_wider(names_from = label, values_from = diff) %>%
    filter(!is.na(after)) %>%
    mutate(id = paste(chrom,loop)) %>%
    arrange(desc(before)) %>%
    slice(1:THRESHES[i]) %>%
    pull(id) %>%
    unique()
  after_loops <- results_lps %>%
    filter(m1=='lps141_1', m2=='lps853_1') %>%
    pivot_wider(names_from = label, values_from = diff) %>%
    filter(!is.na(after)) %>%
    mutate(id = paste(chrom,loop)) %>%
    arrange(desc(after)) %>%
    slice(1:THRESHES[i]) %>%
    pull(id) %>%
    unique()
  cat_res$concordance[i] <- sum(before_loops %in% after_loops)/length(before_loops)
}
cat_res$samples <- 'LPS141_1 & LPS853_1'
final_res <- bind_rows(final_res,cat_res)
cat_res <- data.frame(threshold = THRESHES, concordance = NA)
for (i in seq_along(THRESHES)) {
  before_loops <- results_lps %>%
    filter(m1=='lps141_2', m2=='lps853_2') %>%
    pivot_wider(names_from = label, values_from = diff) %>%
    filter(!is.na(after)) %>%
    mutate(id = paste(chrom,loop)) %>%
    arrange(desc(before)) %>%
    slice(1:THRESHES[i]) %>%
    pull(id) %>%
    unique()
  after_loops <- results_lps %>%
    filter(m1=='lps141_2', m2=='lps853_2') %>%
    pivot_wider(names_from = label, values_from = diff) %>%
    filter(!is.na(after)) %>%
    mutate(id = paste(chrom,loop)) %>%
    arrange(desc(after)) %>%
    slice(1:THRESHES[i]) %>%
    pull(id) %>%
    unique()
  cat_res$concordance[i] <- sum(before_loops %in% after_loops)/length(before_loops)
}
cat_res$samples <- 'LPS141_2 & LPS853_2'
final_res <- bind_rows(final_res,cat_res)

final_res %>%
  ggplot(aes(x = threshold, y = concordance)) +
  geom_point(aes(color=samples)) +
  geom_line(aes(color=samples)) +
  scale_color_tableau(palette = 'Nuriel Stone') +
  coord_cartesian(ylim=c(0,1)) +
  theme_classic()
```



```{r}
final_res %>%
  filter(threshold>=10, threshold <= 10000) %>%
  ggplot(aes(x = threshold, y = concordance)) +
  geom_point(aes(color=samples)) +
  geom_line(aes(color=samples)) +
  scale_color_tableau(name='',palette = 'Nuriel Stone') +
  coord_cartesian(ylim=c(0,1)) +
  scale_x_continuous(breaks = c(THRESHES)) +
  theme_classic() +
  xlab('Top n differential loops') +
  ylab('Concordance before vs. after')
ggsave('cat-plot.pdf', height=3, width=5)
```



```{r}
final_res %>%
  filter(threshold >= 10, threshold <= 50000) %>%
  ggplot(aes(x = factor(threshold, levels = unique(THRESHES), labels = c('1','5','10', '50', '100', '250', '500', '750', '1k', '2.5k', '5k', '7.5k', '10k', '25k', '50k', '75k', '100k')), y = concordance)) +
  geom_point(aes(color=samples)) +
  geom_line(aes(color=samples, group=samples)) +
  scale_color_tableau(name='',palette = 'Nuriel Stone') +
  coord_cartesian(ylim=c(0,1)) +
  scale_x_discrete() +
  theme_classic() +
  xlab('Top n differential loops') +
  ylab('Concordance between samples\nbefore vs. after')
ggsave('cat-plot.pdf', height=3, width=6)
```



