---
output: html_document
---


```{r}
library(dplyr)
library(tidyr)
library(ggplot2)
library(data.table)
library(ggthemes)
library(rtracklayer)
library(RColorBrewer)
MIN_PET=3
```

```{r}
myfiles <- list.files(pattern = 'lps_2500_results_g0.5_chr.*rds')
loops <- NULL
before <- NULL
results <- NULL
after <- NULL
for (f in myfiles) {
  d <- readRDS(f)
  chrom <- unlist(strsplit(unlist(strsplit(f, '_'))[5], '\\.'))[1]
  if (is.null(loops)) {
    loops <- d@loops
  } else {
    loops <- rbind(loops, d@loops)
  }
  if (is.null(before)) {
    before <- d@results$before
  } else {
    before <- rbind(before, d@results$before)
  }
  if (is.null(after)) {
    after <- d@results$after
  } else {
    after <- rbind(after, d@results$after)
  }
  if (is.null(results)) {
    results <- d@results$df %>% mutate(chrom=chrom)
  } else {
    results <- rbind(results, d@results$df %>% mutate(chrom=chrom))
  }
}
```



# Compare before/after


```{r}
results %>%
  pivot_wider(names_from = 'label', values_from = 'diff') %>%
  ggplot(aes(x = before, y = after)) +
  geom_point(alpha=0.25, color='grey') +
  geom_smooth(se=F, color='blue', size=0.5) +
  facet_grid(m1~m2) +
  geom_abline(slope=1, intercept=0, lty='dashed', color = 'red') +
  theme_bw()
ggsave('LPS_pairs.pdf', height=4, width=4, units='in')
```


```{r}
results %>%
  pivot_wider(names_from = 'label', values_from = 'diff') %>%
  ggplot(aes(x = log2(before+1), y = log2(after+1))) +
  geom_point(alpha=0.25, color='grey') +
  geom_smooth(se=F, color='blue', size=0.5) +
  facet_grid(m1~m2) +
  geom_abline(slope=1, intercept=0, lty='dashed', color = 'red') +
  theme_bw() +
  xlab('log2(Before+1)') +
  ylab('log2(After+1)')
ggsave('LPS_pairs_log.pdf', height=4, width=4, units='in')
```



```{r}
results %>%
  filter((m1=='lps141_1' & m2=='lps141_2') | (m1=='lps853_1' & m2=='lps853_2')) %>%
  pivot_wider(names_from = 'label', values_from = 'diff') %>%
  ggplot(aes(x = log2(before), y = log2(after))) +
  geom_point(alpha=0.05, color='grey') +
  geom_smooth(se=F, color='blue', size=0.5) +
  geom_abline(slope=1, intercept=0, lty='dashed', color = 'red') +
  theme_minimal() +
  ggtitle('Between replicate difference')
```


```{r}
results %>%
  filter((m1=='lps141_1' & m2=='lps141_2') | (m1=='lps853_1' & m2=='lps853_2')) %>%
  pivot_wider(names_from = 'label', values_from = 'diff') %>%
  filter(after>before, log2(before)<1)
```

# Compare 



