---
output: html_document
---


```{r}
library(dplyr)
library(tidyr)
library(ggplot2)
library(data.table)
library(ggthemes)
library(rtracklayer)
library(RColorBrewer)
library(dcon)
MIN_PET=3

plot_mat <- function(mat, main='') {
  print(
    reshape2::melt(as.matrix(mat)) %>%
      ggplot(aes(x = Var2, y = Var1)) +
      geom_tile(aes(fill=value),color='grey') +
      scale_fill_gradient(low='white',high='red') +
      theme_classic() +
      xlab('Anchor 1') +
      ylab('Anchor 2') + 
      annotate("rect", xmin = 9.5, xmax = 12.5, ymin = 9.5, ymax = 12.5, color='blue', lty='dashed', fill=NA) +
      ggtitle(main)
  )
  
}
```

```{r}
current_chrom<-'chr2'
loops <- readRDS('../loops.rds')
loops$idx <- seq(1,nrow(loops))
# Load hichip matrices and coordinates
mychroms <- c(paste0('chr',seq(1,22)),'chrX')
coords <- dcon:::load_coords('/rafalab/lzou/hichip_mnase/Deep_HC_YET_17_2.5kb_MatrixHiCPro_abs.bed')
chrom_starts <- coords %>% as.data.frame() %>% group_by(seqnames) %>% dplyr::slice(1)
k562_rep1 <- dcon:::load_hichip('/rafalab/lzou/hichip_mnase/Deep_HC_YET_17_2.5kb_MatrixHiCPro.matrix', coords=coords)
k562_rep2 <- dcon:::load_hichip('/rafalab/lzou/hichip_mnase/Deep_HC_YET_18_2.5kb_MatrixHiCPro.matrix', coords=coords)
hic <- readMM(paste0('/rafalab/lzou/hichip_mnase/K562_HiC_',current_chrom,'_2500.mtx'))
coords <- coords[seqnames(coords)==current_chrom,]
```

```{r, eval=F}
set.seed(1337)
myDcon <- Dcon(mat = list(k562_rep1 = k562_rep1, k562_rep2 = k562_rep2),
               coords = coords,
               loops = loops %>% filter(chr1==current_chrom, label=='k562', (s2-s1)>5e5) %>% sample_n(20),
               hic = hic)
myDcon
```


```{r}
myDconvolved <- deconvolve(myDcon, gamma=0.5, save_mat = T)
```


```{r, eval=F}
for (i in 1:nrow(myDconvolved@loops)) {
  lab <- paste0(paste('chr2',myDconvolved@loops$s1[i], myDconvolved@loops$s2[i], sep=':'), ', PET: ', myDconvolved@loops$pet[i])
  idx1 <- ((i-1)*2)+1
  idx2 <- i*2
  plot_mat(myDconvolved@mat$before[[idx1]], paste(lab,'before,rep1'))
  plot_mat(myDconvolved@mat$after[[idx1]], paste(lab,'after,rep1'))
  plot_mat(myDconvolved@mat$before[[idx2]], paste(lab,'before,rep2'))
  plot_mat(myDconvolved@mat$after[[idx2]], paste(lab,'after,rep2'))
}
```



# Zoom in on chr2:118,202,500 (H3K4me3) x 118,865,000 (CTCF motif)


```{r}
i=8
idx1 <- ((i-1)*2)+1
idx2 <- i*2
lab='chr2:118,202,500 x 118,865,000'
plot_mat(myDconvolved@mat$before[[idx1]], paste(lab,'before,rep1'))
plot_mat(myDconvolved@mat$after[[idx1]], paste(lab,'after,rep1'))
plot_mat(myDconvolved@mat$before[[idx2]], paste(lab,'before,rep2'))
plot_mat(myDconvolved@mat$after[[idx2]], paste(lab,'after,rep2'))
```



# HiChIP chr2 matrix visualization with box indicating the window we are looking at (replicate 1)

Make a 1mb window from 118mb to 119mb

```{r}
a1 <- 118202500
a2 <- 118865000
a1_start <- a1-25000
a1_end <- a1+25000
a2_start <- a2-25000
a2_end <- a2+25000
coords <- dcon:::load_coords('/rafalab/lzou/hichip_mnase/Deep_HC_YET_17_2.5kb_MatrixHiCPro_abs.bed')
k562_rep1 <- dcon:::load_hichip('/rafalab/lzou/hichip_mnase/Deep_HC_YET_17_2.5kb_MatrixHiCPro.matrix', coords=coords, diagonal=0)
coords <- coords[seqnames(coords)==current_chrom,]
subcoords <- coords[start(coords)>=118e6 & end(coords)<=119e6]
chr2_hichip <- k562_rep1[subcoords$id, subcoords$id]
# make symmetric
chr2_hichip <- chr2_hichip + t(chr2_hichip) - diag(diag(chr2_hichip))
as.data.frame(summary(chr2_hichip)) %>%
  ggplot(aes(x = j*2500+118e6, y = -i*2500-118e6)) +
  geom_tile(aes(fill = log2(x+1), color=log2(x+1))) +
  scale_color_gradient('log2(count+1)',low='darkorange', high='firebrick2') +
  scale_fill_gradient('log2(count+1)',low='darkorange', high='firebrick2') +
  scale_x_continuous(expand=c(.01,0), breaks=c(0,100,200,300,400)*2500+118e6, labels = c('118mb', '118.25mb', '118.5mb', '118.75mb', '119mb')) +
  scale_y_continuous(expand=c(.01,0), breaks=c(0,-100,-200,-300,-400)*2500-118e6, labels = c('118mb', '118.25mb', '118.5mb', '118.75mb', '119mb')) +
  theme(
    panel.background = element_blank(),
    panel.grid.major = element_blank(), 
    panel.grid.minor = element_blank(),
    panel.border = element_rect(colour = "black", fill=NA, size=1)) +
  annotate('rect', xmin=a2_start, xmax=a2_end, ymin=-a1_start, ymax=-a1_end, color = 'blue', fill = NA) +
  xlab('') +
  ylab('')
ggsave('k562_hichip_chr2_118mb-119mb.pdf', height=3, width=4.5, units='in')
```


# put before/after side-by-side for each replicate

```{r}
# load in encode cis-cres for plotting on the side
cres <- fread('hg38_encode_ccres_less.bed', header=T, col.names = c('chrom','start','end','ucscLabel'))
cre_colors <- data.frame(ucscLabel = unique(cres$ucscLabel),
                         color = c('gold2', 'gold1', 'red', 'steelblue1', 'hotpink1'))
cres <- cres %>% left_join(cre_colors)
# load in CTCF K562 chip-seq peaks
chip <- fread('/rafalab/lzou/chip/K562_hg38_CTCF_chip_narrowPeak_ENCFF843VHC.bed.gz', header=F, col.names = c('chrom','start','end','idk1','idk2','idk3','idk4','idk5','idk6','idk7')) %>% arrange(chrom, start)
```


## Rep 1 before/after

```{r}
chr2_cres <- cres[cres$chrom=='chr2' & cres$start>=118e6 & cres$end<=119e6]
chr2_chip <- chip[chip$chrom=='chr2' & chip$start>=118e6 & chip$end<=119e6]
a1_cres <- chr2_cres[chr2_cres$start >= a1_start & chr2_cres$end <= a1_end]
a2_cres <- chr2_cres[chr2_cres$start >= a2_start & chr2_cres$end <= a2_end]
a1_chip <- chr2_chip[chr2_chip$start >= a1_start & chr2_chip$end <= a1_end]
a2_chip <- chr2_chip[chr2_chip$start >= a2_start & chr2_chip$end <= a2_end]
a1_cres <- a1_cres %>%
  mutate(x = .1*2500+(a2_start-1250), xend = .1*2500+(a2_start-1250)+5,
         y = -end, yend = -start)
a2_cres <- a2_cres %>%
  mutate(y=-20.9*2500-(a1_start+1250)+5, yend = -20.9*2500-(a1_start+1250),
         x = start, xend = end)
a1_chip <- a1_chip %>%
  mutate(x = 43.1*2500+(a2_start-1250), xend = 43.1*2500+(a2_start-1250),
         y = -end, yend = -start) %>%
  mutate(color='brown')
a2_chip <- a2_chip %>%
  mutate(y = .9*2500-(a1_start+1250), yend = .9*2500-(a1_start+1250),
         x = start, xend = end) %>%
  mutate(color='brown')
cres_plot <- bind_rows(a1_cres, a2_cres) %>%
  bind_rows(a2_cres %>% mutate(x = x+21*2500, xend = xend+21*2500)) %>%
  bind_rows(a1_chip) %>%
  bind_rows(a2_chip) %>%
  bind_rows(a2_chip %>% mutate(x = x+21*2500, xend = xend+21*2500))
i=8
idx1 <- ((i-1)*2)+1
idx2 <- i*2
rep1 <- cbind(
  as.matrix(myDconvolved@mat$before[[idx1]]),
  as.matrix(myDconvolved@mat$after[[idx1]])
)
rep1 %>%
  melt() %>%
  mutate(Var1 = Var1*2500+(a1_start-1250), Var2 = Var2*2500+(a2_start-1250)) %>%
  ggplot(aes(x = Var2, y = -Var1)) +
  geom_tile(aes(fill = value),color='grey') +
  scale_fill_gradient('count',low='white', high='red') +
  theme(panel.background = element_blank(),
    panel.grid.major = element_blank(), 
    panel.grid.minor = element_blank(),
    axis.text.y = element_text(angle=90, hjust=.5),
    axis.ticks = element_blank())+
  scale_x_continuous(breaks=c(11,32)*2500+(a2_start-1250), labels = c('chr2:118,865,000','chr2:118,865,000'),expand=c(0.01,0)) +
  scale_y_continuous(breaks=c(-11*2500-(a1_start-1250)), labels = c('chr2:118,202,500'),expand=c(0.025,0)) +
  geom_vline(xintercept=21.5*2500+(a2_start-1250)) +
  geom_segment(data = cres_plot, aes(x = x, xend = xend, y = y, yend = yend, color = color),size=3)+
  scale_color_identity() +
  annotate('rect',xmin=.5*2500+(a2_start-1250), xmax=42.5*2500+(a2_start-1250), ymin = -21.5*2500-(a1_start-1250), ymax = -.5*2500-(a1_start-1250), fill = NA, color = 'blue') +
  xlab('') +
  ylab('')
ggsave(filename='k562_rep1_before_after.pdf', height=3, width=6, units='in')
```

## Rep 2 before/after


```{r}
rep1 <- cbind(
  as.matrix(myDconvolved@mat$before[[idx2]]),
  as.matrix(myDconvolved@mat$after[[idx2]])
)
rep1 %>%
  melt() %>%
  mutate(Var1 = Var1*2500+(a1_start-1250), Var2 = Var2*2500+(a2_start-1250)) %>%
  ggplot(aes(x = Var2, y = -Var1)) +
  geom_tile(aes(fill = value),color='grey') +
  scale_fill_gradient('count',low='white', high='red') +
  theme(panel.background = element_blank(),
    panel.grid.major = element_blank(), 
    panel.grid.minor = element_blank(),
    axis.text.y = element_text(angle=90, hjust=.5),
    axis.ticks = element_blank())+
  scale_x_continuous(breaks=c(11,32)*2500+(a2_start-1250), labels = c('chr2:118,865,000','chr2:118,865,000'),expand=c(0.01,0)) +
  scale_y_continuous(breaks=c(-11*2500-(a1_start-1250)), labels = c('chr2:118,202,500'),expand=c(0.025,0)) +
  geom_vline(xintercept=21.5*2500+(a2_start-1250)) +
  geom_segment(data = cres_plot, aes(x = x, xend = xend, y = y, yend = yend, color = color),size=3)+
  scale_color_identity() +
  annotate('rect',xmin=.5*2500+(a2_start-1250), xmax=42.5*2500+(a2_start-1250), ymin = -21.5*2500-(a1_start-1250), ymax = -.5*2500-(a1_start-1250), fill = NA, color = 'blue') +
  xlab('') +
  ylab('')
ggsave(filename='k562_rep2_before_after.pdf', height=3, width=6, units='in')
```






