---
output: html_document
---


```{r}
library(data.table)
library(Matrix)
library(dplyr)
library(dcon)
library(GenomicRanges)
library(strawr)
library(rtracklayer)
library(gridExtra)
library(cowplot)


RESOLUTION <- 5000
MIN_DIST <- 20

plot_mat <- function(mat, main='') {
  print(
    reshape2::melt(as.matrix(mat)) %>%
      ggplot(aes(x = Var2, y = Var1)) +
      geom_tile(aes(fill=value),color='grey') +
      scale_fill_gradient(low='white',high='red') +
      theme_classic() +
      xlab('Anchor 1') +
      ylab('Anchor 2') + 
      #annotate("rect", xmin = 9.5, xmax = 12.5, ymin = 9.5, ymax = 12.5, color='blue', lty='dashed', fill=NA) +
      ggtitle(main)
  )
  
}
current_chrom<-'chr2'
```

```{r load-data}
# Load hichip matrices and coordinates
chip.df <- strawr::straw("NONE", "/rafalab/lzou/hichip_gm12878/GM_HiChIP_cohesin_r1.hic", gsub('chr','',current_chrom), gsub('chr','',current_chrom), "BP", RESOLUTION)
chip.df$x <- chip.df$x/RESOLUTION
chip.df$y <- chip.df$y/RESOLUTION
chip.df <- chip.df %>% filter(y-x>3)
chip1 <- sparseMatrix(i = chip.df$x+1, j = chip.df$y+1, x = chip.df$counts)
chip.df <- strawr::straw("NONE", "/rafalab/lzou/hichip_gm12878/GM_HiChIP_cohesin_r2.hic", gsub('chr','',current_chrom), gsub('chr','',current_chrom), "BP", RESOLUTION)
chip.df$x <- chip.df$x/RESOLUTION
chip.df$y <- chip.df$y/RESOLUTION
chip.df <- chip.df %>% filter(y-x>3)
chip2 <- sparseMatrix(i = chip.df$x+1, j = chip.df$y+1, x = chip.df$counts)
coords <- dcon:::load_coords('/rafalab/lzou/resources/hg19.5kb.windows', type='windows')
coords <- coords[seqnames(coords)==current_chrom,]
coords$id <- seq(1,length(coords))
# Load in HiC matrix
hic <- strawr::straw("NONE", "/rafalab/lzou/hichip_gm12878/ENCFF718AWL.hic", gsub('chr','',current_chrom), gsub('chr','',current_chrom), "BP", RESOLUTION)
hic <- sparseMatrix(i = hic$x/RESOLUTION+1, j = hic$y/RESOLUTION+1, x = hic$counts)
# Load in loops
loops <- fread('/rafalab/lzou/hichip_gm12878/fithichip_gm12878_cohesin_loose.csv')
colnames(loops)[1:5] <- c('chr1','s1','e1','s2','e2')
loops$s1 <- floor(loops$s1/RESOLUTION)*RESOLUTION
loops$s2 <- floor(loops$s2/RESOLUTION)*RESOLUTION
loops$e1 <- floor(loops$e1/RESOLUTION)*RESOLUTION
loops$e2 <- floor(loops$e2/RESOLUTION)*RESOLUTION
loops$chr2 <- current_chrom
loops <- loops %>% filter(chr1==current_chrom)
loops <- loops %>% arrange(s1,s2)
loops$bin1 <- loops[,1:3] %>% dplyr::rename(seqnames=chr1, start=s1, end=e1) %>% left_join(as.data.frame(coords)) %>% pull(id)
loops$bin2 <- loops[,c(1,4,5)] %>% dplyr::rename(seqnames=chr1, start=s2, end=e2) %>% left_join(as.data.frame(coords)) %>% pull(id)
loops <- loops %>% filter(bin2-bin1>MIN_DIST)
```

```{r make-dcon-object}
myDcon <- Dcon(mat = list(gm12878_1=chip1, gm12878_2=chip2),
               coords = coords,
               loops = loops %>% slice(1000:1050),
               hic = list(hic))
myDcon
```


```{r}
myDconvolved <- deconvolve(myDcon, df=11, gamma=0.25, save_mat = T, pad=5)
```


```{r, eval=F}
for (i in 1:nrow(myDconvolved@loops)) {
  lab <- paste0(paste('chr2',myDconvolved@loops$s1[i], myDconvolved@loops$s2[i], sep=':'), ', PET: ', myDconvolved@loops$pet[i])
  idx1 <- ((i-1)*2)+1
  idx2 <- i*2
  plot_mat(myDconvolved@mat$before[[idx1]], paste(lab,'before,rep1'))
  plot_mat(myDconvolved@mat$after[[idx1]], paste(lab,'after,rep1'))
  plot_mat(myDconvolved@mat$before[[idx2]], paste(lab,'before,rep2'))
  plot_mat(myDconvolved@mat$after[[idx2]], paste(lab,'after,rep2'))
}
```


```{r}
mys1 <- 38600000
mys2 <- 38735000
myloop <- loops %>% filter(s1==mys1,s2==mys2)
myDcon_one <- Dcon(mat = list(gm12878_1=chip1, gm12878_2=chip2),
                   coords = coords,
                   loops = myloop,
                   hic = list(hic))
myDconvolved_one <- deconvolve(myDcon_one, gamma=1, save_mat = T, pad=5, df=11)
```


```{r}
reshape2::melt(as.matrix(myDconvolved_one@mat$before[[1]])) %>%
  mutate(type = 'Before') %>%
  rbind(reshape2::melt(as.matrix(myDconvolved_one@mat$after[[1]])) %>%
          mutate(type = 'After')) %>%
  mutate(type = factor(type, levels = c('Before','After'))) %>%
  ggplot(aes(x = Var2*5000+mys2-50000, y = Var1*5000+mys1-50000)) +
  geom_tile(aes(fill=value),color='grey') +
  scale_fill_gradient(name='Count',low='white',high='red') +
  facet_wrap( type ~ .) +
  theme_minimal() +
  theme(axis.ticks = element_blank(), axis.line.x = element_blank(), axis.line.y = element_blank(),
        panel.grid = element_blank()) +
  xlab('Anchor 1') +
  ylab('Anchor 2') + 
  # annotate("rect", xmin = 9.5*5000+mys2-50000, xmax = 12.5*5000+mys2-50000, ymin = 9.5*5000+mys1-50000, ymax = 12.5*5000+mys1-50000, color='blue', lty='dashed', fill=NA) +
  # annotate("rect", xmin = 30.5*5000+mys2-50000, xmax = 33.5*5000+mys2-50000, ymin = 9.5*5000+mys1-50000, ymax = 12.5*5000+mys1-50000, color='blue', lty='dashed', fill=NA) +
  scale_x_continuous(labels=NULL) +
  scale_y_continuous(labels=NULL, trans='reverse') +
  # geom_segment(data=r1_chip, aes(x = 184185000-50000, xend = mys2-50000, y = start, yend=end), color='brown',size=3) +
  # geom_segment(data=r2_chip, aes(x = start, xend = end, y = 183615000-50000, yend=mys1-50000), color='brown',size=3) +
  ylab(paste0('chr2:', prettyNum(mys1-2.5e4, big.mark=','), '-', prettyNum(mys1+2.5e4, big.mark=','))) +
  xlab(paste0('chr2:', prettyNum(mys2-2.5e4, big.mark=','), '-', prettyNum(mys2+2.5e4, big.mark=','))) +
  ggtitle('Replicate 1: Before | After')
ggsave(file='gm12878_cohesin_rep1_example_loop.pdf', height=3, width=6)
```


```{r}
reshape2::melt(as.matrix(myDconvolved_one@mat$before[[2]])) %>%
  mutate(type = 'Before') %>%
  rbind(reshape2::melt(as.matrix(myDconvolved_one@mat$after[[2]])) %>%
          mutate(type = 'After')) %>%
  mutate(type = factor(type, levels = c('Before','After'))) %>%
  ggplot(aes(x = Var2*5000+mys2-50000, y = Var1*5000+mys1-50000)) +
  geom_tile(aes(fill=value),color='grey') +
  scale_fill_gradient(name='Count',low='white',high='red') +
  facet_wrap( type ~ .) +
  theme_minimal() +
  theme(axis.ticks = element_blank(), axis.line.x = element_blank(), axis.line.y = element_blank(),
        panel.grid = element_blank()) +
  xlab('Anchor 1') +
  ylab('Anchor 2') + 
  # annotate("rect", xmin = 9.5*5000+mys2-50000, xmax = 12.5*5000+mys2-50000, ymin = 9.5*5000+mys1-50000, ymax = 12.5*5000+mys1-50000, color='blue', lty='dashed', fill=NA) +
  # annotate("rect", xmin = 30.5*5000+mys2-50000, xmax = 33.5*5000+mys2-50000, ymin = 9.5*5000+mys1-50000, ymax = 12.5*5000+mys1-50000, color='blue', lty='dashed', fill=NA) +
  scale_x_continuous(labels=NULL) +
  scale_y_continuous(labels=NULL, trans='reverse') +
  # geom_segment(data=r1_chip, aes(x = 184185000-50000, xend = mys2-50000, y = start, yend=end), color='brown',size=3) +
  # geom_segment(data=r2_chip, aes(x = start, xend = end, y = 183615000-50000, yend=mys1-50000), color='brown',size=3) +
  ylab(paste0('chr2:', prettyNum(mys1-2.5e4, big.mark=','), '-', prettyNum(mys1+2.5e4, big.mark=','))) +
  xlab(paste0('chr2:', prettyNum(mys2-2.5e4, big.mark=','), '-', prettyNum(mys2+2.5e4, big.mark=','))) +
  ggtitle('Replicate 2: Before | After')
ggsave(file='gm12878_cohesin_rep2_example_loop.pdf', height=3, width=6)
```


```{r}
rad21_peaks <- fread('/rafalab/lzou/chip/ENCFF002CPK_RAD21_GM12878_hg19.bed', col.names = c('chrom','start','end','idk4','idk5','idk6','idk7','idk8','idk9','idk10')) %>%
  filter(chrom=='chr2')
rad21_r1 <- rad21_peaks %>% filter(start>=mys1-2.5e4, start<=mys1+2.5e4)
rad21_r2 <- rad21_peaks %>% filter(start>=mys2-2.5e4, start<=mys2+2.5e4)
```


```{r}
# chip-seq for that region
rad21 <- import('/rafalab/lzou/chip/ENCFF000WCT_RAD21_GM12878_hg19.bigWig')
rad21 <- rad21[seqnames(rad21)=='chr2']
smc3 <- import('/rafalab/lzou/chip/ENCFF815ERA_SMC3_GM12878_hg19.bigWig')
smc3 <- smc3[seqnames(smc3)=='chr2']
ctcf <- import('/rafalab/lzou/chip/ENCFF749HDD_CTCF_GM12878_hg19.bigWig')
ctcf <- ctcf[seqnames(ctcf)=='chr2']

rad21_r1 <- rad21[(start(rad21) >= mys1-2.5e4) & (start(rad21) <= mys1+3e4)]
smc3_r1 <- smc3[(start(smc3) >= mys1-2.5e4) & (start(smc3) <= mys1+3e4)]
ctcf_r1 <- ctcf[(start(ctcf) >= mys1-2.5e4) & (start(ctcf) <= mys1+3e4)]

rad21_r2 <- rad21[(start(rad21) >= mys2-2.5e4) & (start(rad21) <= mys2+3e4)]
smc3_r2 <- smc3[(start(smc3) >= mys2-2.5e4) & (start(smc3) <= mys2+3e4)]
ctcf_r2 <- ctcf[(start(ctcf) >= mys2-2.5e4) & (start(ctcf) <= mys2+3e4)]
```

```{r}
p1 <- as.data.frame(rad21_r1) %>%
  ggplot(aes(x = start, y= score)) +
  geom_bar(stat='identity',fill='blue',color='blue') +
  theme_classic() +
  theme(axis.ticks.x = element_blank(),
        axis.text.x = element_blank()) +
  scale_x_continuous(trans='reverse') +
  xlab('') +
  ylab('RAD21')
# p2 <- as.data.frame(smc3_r1) %>%
#   ggplot(aes(x = start, y= score)) +
#   geom_bar(stat='identity',fill='blue',color='blue') +
#   theme_classic() +
#   theme(axis.ticks.x = element_blank(),
#         axis.text.x = element_blank(),
#         plot.margin=unit(c(0,1,0,1), "cm")) +
#   xlab('') +
#   ylab('SMC3')
# p3 <- as.data.frame(ctcf_r1) %>%
#   ggplot(aes(x = start, y= score)) +
#   geom_bar(stat='identity',fill='blue',color='blue') +
#   theme_classic() +
#   theme(plot.margin=unit(c(0,1,1,1), "cm")) +
#   xlab('') +
#   ylab('CTCF')
# plot_grid(p1, p2, p3, align='v', nrow=3, rel_heights = c(1/3,1/3,1/3))
p1
ggsave('gm12878_cohesin_rad21_chipseq_example_r1.pdf', height=1, width=2.5)
```

```{r}
p1 <- as.data.frame(rad21_r2) %>%
  ggplot(aes(x = start, y= score)) +
  geom_bar(stat='identity',fill='blue',color='blue') +
  theme_classic() +
  theme(axis.ticks.x = element_blank(),
        axis.text.x = element_blank()) +
  scale_x_continuous() +
  xlab('') +
  ylab('RAD21')
# p2 <- as.data.frame(smc3_r2) %>%
#   ggplot(aes(x = start, y= score)) +
#   geom_bar(stat='identity',fill='blue',color='blue') +
#   theme_classic() +
#   xlab('') +
#   ylab('SMC3')
# p3 <- as.data.frame(ctcf_r2) %>%
#   ggplot(aes(x = start, y= score)) +
#   geom_bar(stat='identity',fill='blue',color='blue') +
#   theme_classic() +
#   xlab('') +
#   ylab('CTCF')
# grid.arrange(p1,p2,p3, nrow=3)
p1
ggsave('gm12878_cohesin_rad21_chipseq_example_r2.pdf', height=1, width=3)
```





