---
output: html_document
params:
  chrom: 'chr1'
---


```{r load-libraries-and-data}
library(dplyr)
library(ggplot2)
library(reshape2)
library(tidyr)
library(data.table)
library(Matrix)
library(RColorBrewer)
library(dcon)
library(rtracklayer)
library(InteractionSet)
```

```{r,eval=F}
load('/rafalab/lzou/dcon/hiplastic/shiny_data_v2.RData')
OE_mat <- OE_mat + t(OE_mat) - diag(diag(OE_mat))
l1md_chr18 <- l1md_chr18 + t(l1md_chr18) - diag(diag(l1md_chr18))
total_DNA_chr18 <- total_DNA_chr18 + t(total_DNA_chr18) - diag(diag(total_DNA_chr18))
b1_annot <- fread('/rafalab/lzou/resources/mm10.100kb.windows.B1.coverage',
                  col.names = c('chrom','start','end','nfeatures', 'nbp',
                                'tot', 'frac')) |>
  filter(chrom=='chr18')
l1_annot <- fread('/rafalab/lzou/resources/mm10.100kb.windows.L1.coverage',
                  col.names = c('chrom','start','end','nfeatures', 'nbp',
                                'tot', 'frac')) |>
  filter(chrom=='chr18')
l1md_annot <- fread('/rafalab/lzou/resources/mm10.100kb.windows.L1Md.coverage',
                    col.names = c('chrom','start','end','nfeatures', 'nbp',
                                  'tot', 'frac'))|>
  filter(chrom=='chr18')
l1md_bed <- fread('/rafalab/lzou/resources/L1Md_mm10.rmsk.annot.bed',
                  col.names = c('chrom','start','end','element')) |>
  filter(chrom=='chr18') |>
  arrange(start)
windows <- fread('/rafalab/lzou/resources/mm10.100kb.windows', 
                 col.names = c('chrom','start','end')) |>
  filter(chrom=='chr18')

rna_offset <- fread('/rafalab/lzou/rdsprite/total_RNA_count_windows_100000_clusters_2-100.csv') |>
  filter(chrom=='chr18') |>
  select(-V1)

total_l1_rna <- fread('/rafalab/lzou/rdsprite/count_windows/L1,LINE|LINE,L1_RNA_count_windows_100000_clusters_2-100.csv') |>
  filter(chrom=='chr18')
total_l1md_rna <- fread('/rafalab/lzou/rdsprite/count_windows/L1Md_RNA_count_windows_100000_clusters_2-100.csv') |>
  filter(chrom=='chr18')
total_b1_rna <- fread('/rafalab/lzou/rdsprite/count_windows/Alu,SINE|SINE,Alu_RNA_count_windows_100000_clusters_2-100.csv') |>
  filter(chrom=='chr18')
```

# First establish that chr18 works


```{r,eval=F}
l1md_annot$total_rna <- rna_offset$count
l1md_annot$b1_frac <- b1_annot$frac
l1md_annot$l1_frac <- l1_annot$frac
l1md_annot$l1md_rna <- total_l1md_rna$count
l1md_annot$b1_rna <- total_b1_rna$count
l1md_annot$l1_rna <- total_l1_rna$count
l1md_annot$avg_oe <- rowMeans(OE_mat)
```


```{r,eval=F}
# look at the top 50 l1md RNA/total bins
top_10 <- l1md_annot %>%
  mutate(idx = 1:908) %>%
  arrange(desc(l1md_rna/total_rna)) %>%
  slice(1:50) %>%
  pull(idx)
cbind(l1md_annot, as.data.frame(as.matrix(OE_mat[,top_10]))) %>%
  pivot_longer(cols = starts_with('V'), names_to = 'top_idx', values_to = 'OE') %>%
  ggplot(aes(x = l1md_rna/total_rna, y = OE)) +
  geom_point(alpha=0.25, color='grey') +
  geom_smooth(aes(group = top_idx),se=F,alpha=0.5,color='black',size=0.5) +
  geom_hline(yintercept=1, lty='dashed', color='red') +
  theme_classic()
```

```{r,eval=F}
cbind(l1md_annot, as.data.frame(as.matrix(OE_mat[,top_10]))) %>%
  pivot_longer(cols = starts_with('V'), names_to = 'top_idx', values_to = 'OE') %>%
  mutate(l1md_bin = cut_number(l1md_rna/total_rna, 10)) %>%
  filter(!is.na(l1md_bin)) %>%
  ggplot(aes(x = l1md_bin, y = OE)) +
  #geom_point(alpha=0.25, color='grey') +
  geom_boxplot() +
  #geom_smooth(aes(group = top_idx),se=F,alpha=0.5,color='black',size=0.5) +
  geom_hline(yintercept=1, lty='dashed', color='red') +
  theme_classic()
```



```{r,eval=F}
# look at the top bottom l1md RNA/total bins
bot_10 <- l1md_annot %>%
  mutate(idx = 1:908) %>%
  arrange((l1md_rna/total_rna)) %>%
  slice(1:50) %>%
  pull(idx)
cbind(l1md_annot, as.data.frame(as.matrix(OE_mat[,bot_10]))) %>%
  pivot_longer(cols = starts_with('V'), names_to = 'top_idx', values_to = 'OE') %>%
  ggplot(aes(x = l1md_rna/total_rna, y = OE)) +
  geom_point(alpha=0.25, color='grey') +
  geom_smooth(aes(group = top_idx),se=F,alpha=0.5,color='black',size=0.5) +
  geom_hline(yintercept=1, lty='dashed', color='red') +
  theme_classic()
```


```{r,eval=F}
# deconvolve half-overlapping 2mb windows around the top 50 bins
myidx <- data.frame(center = c(top_10, bot_10), upper = c(top_10, bot_10)+10,
                    lower = c(top_10, bot_10)-10)
myidx$upper[myidx$upper>908] <- 908
# all 2mb windows 
all2mb <- data.frame(lower = seq(1,908-21,21), upper = seq(21,908,21))
fitted_results <- list()
for (i in 1:nrow(myidx)) {
  message(i)
  fitted_results[[paste0(i)]] <- list()
  idx1 <- myidx$lower[i]:myidx$upper[i]
  offset1 <- rna_offset$count[idx1]
  for (j in 1:nrow(all2mb)) {
    idx2 <- all2mb$lower[j]:all2mb$upper[j]
    if (any(idx1 %in% idx2)) {
      next
    }
    offset2 <- rna_offset$count[idx2]
    mat <- l1md_chr18[idx1,idx2]
    y1 <- rowSums(mat)
    D1 <- dcon:::normalize_hic(total_DNA_chr18[idx1,idx1], gamma=0.8)
    y2 <- colSums(mat)
    D2 <- dcon:::normalize_hic(total_DNA_chr18[idx2,idx2], gamma=0.8)
    B1 <- dcon:::construct_basis(1:length(y1), df = length(y1))
    B2 <- dcon:::construct_basis(1:length(y2), df = length(y2))
    df1 <- length(y1)
    df2 <- length(y2)
    fit1 <- try(dcon:::fit_decon(y1, D1, df = df1, offset=offset1), silent=T)
    fit2 <- try(dcon:::fit_decon(y2, D2, df = df2, offset=offset2), silent=T)
    if (is(fit1, 'try-error') | is(fit2, 'try-error')) {
      next
    }
    a1 <- fit1$a
    predicted1 <- (B1%*%a1)
    a2 <- fit2$a
    predicted2 <- (B2%*%a2)
    res <- exp(matrix(data = rep(predicted1, df1), nrow=df2, ncol=df1) + 
                 t(matrix(data = rep(predicted2, df2), nrow = df1, ncol = df2)))
    add_this <- list()
    add_this[[paste0(j)]] <- res
    fitted_results[[paste0(i)]] <- append(fitted_results[[paste0(i)]], add_this)
  }
}
```


```{r,eval=F}
# combine the middles
all_results <- matrix(NA, nrow = 908, ncol = 100)
for (i in names(fitted_results)) {
  for (j in names(fitted_results[[i]])) {
    idx_col <- as.integer(i)
    idx_row <- as.integer(j)
    start_row <- all2mb$lower[idx_row]
    end_row <- all2mb$upper[idx_row]
    all_results[start_row:end_row,idx_col] <- fitted_results[[i]][[j]][,11]
  }
}
colnames(all_results) <- c(paste0('top_',c(1:50)), paste0('bottom_',c(1:50)))
```


```{r,eval=F}
dd_top <- bind_cols(melt(all_results[,1:50]) %>% dplyr::rename(id = Var2, deconvolved = value), melt(as.data.frame(as.matrix(OE_mat[,top_10]))) %>% dplyr::rename(OE = value) %>% select(OE)) 
dd_bot <- bind_cols(melt(all_results[,51:100]) %>% dplyr::rename(id = Var2, deconvolved = value), melt(as.data.frame(as.matrix(OE_mat[,bot_10]))) %>% dplyr::rename(OE = value) %>% select(OE)) 
dd <- bind_rows(dd_top, dd_bot)
dd$l1md_rna <- rep(l1md_annot$l1md_rna, times=100)
dd$frac <- rep(l1md_annot$frac, times=100)
dd %>%
  separate(id, into=c('type','id')) %>%
  filter(!is.na(deconvolved)) %>%
  mutate(deconvolved_bin = cut_number(deconvolved, 5)) %>%
  ggplot(aes(x = deconvolved_bin, y = OE)) +
  geom_boxplot(aes(fill=type)) +
  geom_hline(yintercept=1, lty='dashed', color='red') +
  scale_fill_tableau() +
  coord_cartesian(ylim=c(0,2)) +
  theme_classic()
```


```{r,eval=F}
cbind(l1md_annot, as.data.frame(as.matrix(OE_mat[,c(top_10, bot_10)]))) %>%
  pivot_longer(cols = starts_with('V'), names_to = 'idx', values_to = 'OE') %>%
  mutate(idx = as.integer(gsub('V','',idx))) %>%
  mutate(type = ifelse(idx<=50, 'top', 'bottom')) %>%
  mutate(l1md_bin = cut_number(l1md_rna/total_rna, 5)) %>%
  mutate(able_to_be_deconvolved = dd$deconvolved) %>%
  filter(!is.na(able_to_be_deconvolved)) %>%
  filter(!is.na(l1md_bin)) %>%
  ggplot(aes(x = l1md_bin, y = OE)) +
  geom_boxplot(aes(fill = type)) +
  scale_fill_tableau() +
  coord_cartesian(ylim=c(0,2)) +
  geom_hline(yintercept=1, lty='dashed', color='red') +
  theme_classic()
```



# Repeat the above for all chromosomes

## First get the top 50 and bottom 50 L1Md/total RNA bins for each chromosome

```{r}
windows <- fread('/rafalab/lzou/rdsprite/dna_matrix/mm10.100kb.windows', header=F, col.names=c('chrom','start','end'))
windows$idx <- seq(1,nrow(windows))
l1 <- readMM('/rafalab/lzou/rdsprite/dna_matrix/L1,LINE|LINE,L1_DNA_matrix_count_RNA_100000_clusters_2-100.mtx')
l1md <- readMM('/rafalab/lzou/rdsprite/dna_matrix/L1Md_DNA_matrix_count_RNA_100000_clusters_2-100.mtx')
b1 <- readMM('/rafalab/lzou/rdsprite/dna_matrix/Alu,SINE|SINE,Alu_DNA_matrix_count_RNA_100000_clusters_2-100.mtx')
total <- readMM('/rafalab/lzou/rdsprite/dna_matrix/All_DNA_matrix_count_RNA_100000_clusters_2-100.mtx')
total_DNA <- readMM('/rafalab/lzou/rdsprite/total_DD_DNA_matrix_100000_clusters_2-100.mtx')
```

```{r}
chro <- params$chrom
before <- NULL
after <- NULL
message(paste0('doing chromosome ', chro))
windows_idx <- windows$idx[windows$chrom==chro]
nbins <- length(windows_idx)
# subset the df's
l1md_chr <- l1md[windows_idx,windows_idx]
total_DNA_chr <- as(total_DNA[windows_idx,windows_idx], 'dgCMatrix')
# get a basic observed/expected matrix
dd <- summary(total_DNA_chr) %>%
  mutate(dist = j-i)
expec <- dd %>%
  group_by(dist) %>%
  summarise(expected = mean(x))
dd <- dd %>%
  left_join(expec, by = 'dist') %>%
  mutate(OE = x/expected)
OE_mat <- sparseMatrix(i=dd$i, j= dd$j, x = dd$OE, dims=c(nbins,nbins))
# make the matrices symmetric
OE_mat <- OE_mat + t(OE_mat) - diag(diag(OE_mat))
l1md_chr <- l1md_chr + t(l1md_chr) - diag(diag(l1md_chr))
total_DNA_chr <- total_DNA_chr + t(total_DNA_chr) - diag(diag(total_DNA_chr))
# more data to load in
l1md_annot <- fread('/rafalab/lzou/resources/mm10.100kb.windows.L1Md.coverage',
                    col.names = c('chrom','start','end','nfeatures', 'nbp',
                                  'tot', 'frac'))|>
  filter(chrom==chro)
windows <- fread('/rafalab/lzou/resources/mm10.100kb.windows', 
                 col.names = c('chrom','start','end')) |>
  filter(chrom==chro)
rna_offset <- fread('/rafalab/lzou/rdsprite/total_RNA_count_windows_100000_clusters_2-100.csv') |>
  filter(chrom==chro) |>
  select(-V1)
total_l1md_rna <- fread('/rafalab/lzou/rdsprite/count_windows/L1Md_RNA_count_windows_100000_clusters_2-100.csv') |>
  filter(chrom==chro)
l1md_annot$total_rna <- rna_offset$count
l1md_annot$l1md_rna <- total_l1md_rna$count
# get the top 10 and bottom 10 windows with the largest fraction of L1Md/Total RNA
top_10 <- l1md_annot %>%
  mutate(idx = 1:nbins) %>%
  arrange(desc(l1md_rna/total_rna)) %>%
  dplyr::slice(1:50) %>%
  pull(idx)
bot_10 <- l1md_annot %>%
  mutate(idx = 1:nbins) %>%
  arrange((l1md_rna/total_rna)) %>%
  dplyr::slice(1:50) %>%
  pull(idx)
before <- cbind(l1md_annot, as.data.frame(as.matrix(OE_mat[,c(top_10, bot_10)]))) %>%
  pivot_longer(cols = starts_with('V'), names_to = 'idx', values_to = 'OE') %>%
  mutate(idx = as.integer(gsub('V','',idx))) %>%
  mutate(type = ifelse(idx<=50, 'top', 'bottom')) %>%
  mutate(chrom = chro)
# deconvolve the windows around the top bins
# deconvolve half-overlapping 2mb windows around the top 50 bins
myidx <- data.frame(center = c(top_10, bot_10), upper = c(top_10, bot_10)+10,
                    lower = c(top_10, bot_10)-10)
myidx$upper[myidx$upper>nbins] <- nbins # truncate at the end
# all 2mb windows 
# 21 because we're doing 2mb around the center 100kb bin
all2mb <- data.frame(lower = seq(1,nbins-21,21), upper = seq(21,nbins,21))
fitted_results <- list()
for (i in 1:nrow(myidx)) {
  message(i)
  fitted_results[[paste0(i)]] <- list()
  idx1 <- myidx$lower[i]:myidx$upper[i]
  offset1 <- rna_offset$count[idx1]
  for (j in 1:nrow(all2mb)) {
    idx2 <- all2mb$lower[j]:all2mb$upper[j]
    if (any(idx1 %in% idx2)) {
      next
    }
    offset2 <- rna_offset$count[idx2]
    mat <- l1md_chr[idx1,idx2]
    y1 <- rowSums(mat)
    D1 <- dcon:::normalize_hic(total_DNA_chr[idx1,idx1], gamma=0.8)
    y2 <- colSums(mat)
    D2 <- dcon:::normalize_hic(total_DNA_chr[idx2,idx2], gamma=0.8)
    B1 <- dcon:::construct_basis(1:length(y1), df = length(y1))
    B2 <- dcon:::construct_basis(1:length(y2), df = length(y2))
    df1 <- length(y1)
    df2 <- length(y2)
    fit1 <- try(dcon:::fit_decon(y1, D1, df = df1, offset=offset1), silent=T)
    fit2 <- try(dcon:::fit_decon(y2, D2, df = df2, offset=offset2), silent=T)
    if (is(fit1, 'try-error') | is(fit2, 'try-error')) {
      next
    }
    a1 <- fit1$a
    predicted1 <- (B1%*%a1)
    a2 <- fit2$a
    predicted2 <- (B2%*%a2)
    res <- exp(matrix(data = rep(predicted1, df1), nrow=df2, ncol=df1) + 
                 t(matrix(data = rep(predicted2, df2), nrow = df1, ncol = df2)))
    add_this <- list()
    add_this[[paste0(j)]] <- res
    fitted_results[[paste0(i)]] <- append(fitted_results[[paste0(i)]], add_this)
  }
}
# combine the middles
all_results <- matrix(NA, nrow = nbins, ncol = 100)
for (i in names(fitted_results)) {
  for (j in names(fitted_results[[i]])) {
    idx_col <- as.integer(i)
    idx_row <- as.integer(j)
    start_row <- all2mb$lower[idx_row]
    end_row <- all2mb$upper[idx_row]
    all_results[start_row:end_row,idx_col] <- fitted_results[[i]][[j]][,11]
  }
}
colnames(all_results) <- c(paste0('top_',c(1:50)), paste0('bottom_',c(1:50)))
dd_top <- bind_cols(melt(all_results[,1:50]) %>% dplyr::rename(id = Var2, deconvolved = value), melt(as.data.frame(as.matrix(OE_mat[,top_10]))) %>% dplyr::rename(OE = value) %>% select(OE)) 
dd_bot <- bind_cols(melt(all_results[,51:100]) %>% dplyr::rename(id = Var2, deconvolved = value), melt(as.data.frame(as.matrix(OE_mat[,bot_10]))) %>% dplyr::rename(OE = value) %>% select(OE)) 
dd <- bind_rows(dd_top, dd_bot)
dd$l1md_rna <- rep(l1md_annot$l1md_rna, times=100)
dd$frac <- rep(l1md_annot$frac, times=100)
after <- dd %>%
  separate(id, into=c('type','id')) %>%
  mutate(chrom = chro)

save(before, after, file = paste0('l1md_decon_',chro,'.RData'))
```





