---
title: "HiChIP loop strengthening K562 MNase CTCF"
output: html_document
params:
  chrom: 'chr22'
---


This vignette demonstrates how to use deconvolution to perform HiChIP
loop strengthening. The input is HiChIP sparse matrices, loop anchors,
and HiC. The output is the before-deconvolution count and the 
post-deconvolution pseudocount PETs for each input loop.



```{r load-libraries}
library(data.table)
library(Matrix)
library(dplyr)
library(dcon)
library(GenomicRanges)
library(strawr)


current_chrom <- params$chrom
RESOLUTION <- 2500
MIN_DIST <- 40
```


```{r load-data}
mychroms <- c(paste0('chr',seq(1,22)),'chrX')
coords <- dcon:::load_coords('/rafalab/lzou/hichip_mnase/Deep_HC_YET_17_2.5kb_MatrixHiCPro_abs.bed')
k562_rep1 <- dcon:::load_hichip('/rafalab/lzou/hichip_mnase/Deep_HC_YET_17_2.5kb_MatrixHiCPro.matrix', coords=coords, chrom = current_chrom)
k562_rep2 <- dcon:::load_hichip('/rafalab/lzou/hichip_mnase/Deep_HC_YET_18_2.5kb_MatrixHiCPro.matrix', coords=coords, chrom = current_chrom)
# Load in FitHiChIP loops
coords <- coords[seqnames(coords)==current_chrom,]
coords$id <- seq(1,length(coords))
loops <- dcon:::load_anchors('/rafalab/lzou/hichip_mnase/Deep_HC_YET_17_S1_2.5kb.interactions_FitHiC.bed', '/rafalab/lzou/hichip_mnase/Deep_HC_YET_18_S2_2.5kb.interactions_FitHiC.bed', coords=coords)
loops <- loops %>% 
  filter(bin2-bin1>MIN_DIST) %>%
  filter(chr1==current_chrom)
hic <- readMM(paste0('/rafalab/lzou/hichip_mnase/K562_HiC_',current_chrom,'_2500.mtx'))
hic <- as(hic, 'dgTMatrix')
hic <- as(hic, 'dgCMatrix')
```

```{r make-dcon-object}
myDcon <- Dcon(mat = list(k562_1=k562_rep1, k562_2=k562_rep2),
               coords = coords,
               loops = loops,
               hic = list(hic))
myDcon
```



```{r}
myDconvolved <- dcon::deconvolve(myDcon, gamma=0.5, pad=10, store_sum = T)
```



```{r}
saveRDS(myDconvolved, file=paste0('k562_ctcf_2500_results_sum_gamma0.5_',current_chrom,'.rds'))
```

