---
title: "Untitled"
output: html_document
date: "2022-12-10"
params:
  start: 100e6
  end: 110e6
  gamma: 0.8
  df: 50
  mol: 'Alu,SINE|SINE,Alu_DNA_matrix_count_RNA_10000_clusters_2-100000_chrX_129S1_SvImJmtx.mtx'
---

```{r load-libraries-and-data}
library(dplyr)
library(ggplot2)
library(reshape2)
library(tidyr)
library(data.table)
library(Matrix)
library(dcon)
message(params)
```


```{r}
mol_name <- unlist(strsplit(params$mol, '_'))[1]
if (grepl('rds$', params$mol)) {
  mol <- readRDS(paste0('/rafalab/lzou/rdsprite/dna_matrix/', params$mol))
} else if (grepl('mtx$', params$mol)) {
  mol <- readMM(paste0(params$mol))
} else {
  stop('bad input')
}
total_DNA <- readMM('/rafalab/lzou/rdsprite/dna_matrix/total_all_DNA_matrix_10000_clusters_2-100000_chrchrX.mtx')
windows <- fread('/rafalab/lzou/rdsprite/dna_matrix/mm10.10kb.windows', header=F, col.names=c('chrom','start','end'))
windows$idx <- seq(1,nrow(windows))
tot <- total_DNA + t(total_DNA) - Diagonal(x=diag(total_DNA))
mol <- mol + t(mol) - Diagonal(x=diag(mol))
```

```{r}
idx <- windows$idx[which(windows$chrom=='chrX' & windows$start >= as.numeric(params$start) & windows$end <= as.numeric(params$end))]
idx2 <- idx-min(windows$idx[which(windows$chrom=='chrX')])+1
```

## Deconvolved 1D no offset

```{r}
if (grepl('rds$', params$mol)) {
  mat <- mol[idx2,idx2]
} else if (grepl('mtx$', params$mol)) {
  mat <- mol[idx,idx]
} else {
  stop('bad input')
}
norm_tot <- dcon:::normalize_hic(tot[idx,idx], gamma=params$gamma)
y1 <- rowSums(mat)
fit1 <- dcon:::fit_decon(y1, norm_tot, df = params$df)
```

## save to look at in IGV

```{r}
data.frame(
  chrom = 'chrX',
  start = (windows[idx,] %>% pull(start)),
  end = (windows[idx,] %>% pull(end)),
  value = y1
) %>%
  write.table(file = paste0(mol_name,'_raw_',params$start,'_',params$end,'.bedgraph'), quote = F, sep = '\t', row.names = F, col.names=F)
data.frame(
  chrom = 'chrX',
  start = (windows[idx,] %>% pull(start)),
  end = (windows[idx,] %>% pull(end)),
  value = exp(fit1$est)
) %>%
  write.table(file = paste0(mol_name,'_fit_',paste(params, collapse='_'),'.bedgraph'), quote = F, sep = '\t', row.names = F, col.names=F)
```

