---
output: html_document
---

```{r}
library(dcon)
library(Matrix)
library(ggthemes)
```


```{r recovering-signal-ex}
set.seed(1)
LEN=20
DF=15
y <- dcon:::simulate_y(LEN, df = DF, alpha_mean = 1, alpha_sd=3)
fit5 <- dcon:::fit_decon(y$y, y$D, df = 5)
fit10 <- dcon:::fit_decon(y$y, y$D, df = 10)
fit15 <- dcon:::fit_decon(y$y, y$D, df = 15)
fit20 <- dcon:::fit_decon(y$y, y$D, df = 20)
data.frame(x = c(1:LEN),
           observed_count = y$y,
           true_signal = exp(y$B%*%y$a),
           est_signal5 = exp(dcon:::construct_basis(1:LEN, 5)%*%fit5$a),
           est_signal10 = exp(dcon:::construct_basis(1:LEN, 10)%*%fit10$a),
           est_signal15 = exp(dcon:::construct_basis(1:LEN, 15)%*%fit15$a),
           est_signal20 = exp(dcon:::construct_basis(1:LEN, 20)%*%fit20$a)) %>%
  pivot_longer(cols = 2:7, names_to = 'type', values_to = 'y') %>%
  ggplot(aes(x = x, y = y)) +
  geom_point(aes(color = type)) +
  geom_line(aes(color = type)) +
  scale_color_manual(name='', breaks = c('true_signal', 'observed_count',
                                         'est_signal5', 'est_signal10',
                                         'est_signal15', 'est_signal20'),
                     labels = c('True', 'Observed', 'Deconvolved (df=5)',
                                '(df=10)', '(df=15)',
                                '(df=20)'),
                     values = c('#E15759', '#F28E2B', '#A0CBE8', '#83afd2',
                                '#6894bd', '#4e79a7')) +
  # scale_color_tableau(name = '', breaks = c('true_signal', 'observed_count', 'est_signal'),
  #                     labels = c('True', 'Observed', 'Deconvolved')) +
  scale_x_continuous(breaks=c(1,20)) +
  coord_cartesian(ylim=c(0,500)) +
  theme_classic() +
  theme(legend.position = 'bottom') +
  xlab('Position') +
  ylab('Count')
ggsave(file = 'example-deconvolve.pdf', height = 2.5, width= 4, units='in')
```


```{r recovering-signal-ex-hic}
melt(y$D) %>%
  dplyr::rename(x = Var2, y = Var1) %>%
  ggplot(aes(x = x, y = y)) +
  geom_raster(aes(fill = value)) +
  scale_y_reverse() +
  scale_fill_gradient_tableau('Red-Gold', limits = c(0,0.3)) +
  theme_classic() +
  theme(axis.text = element_blank(),
        axis.ticks = element_blank(),
        axis.line = element_blank(),
        legend.position='none') +
  xlab('') +
  ylab('')
ggsave(file = 'example-deconvolve-D.pdf', height = 3, width=3, units='in')
```


```{r}
# A version with 
```




```{r recovering-signal-simulation-df}
# Assuming D is known
# fixed length
# vary DF
set.seed(1337)
B <- 10000
LEN <- 20
DF <- 20
all_res <- NULL
for (i in seq(5,20,5)) {
  mydf <- i
  res <- t(replicate(B, {
    y <- dcon:::simulate_y(LEN, df = DF, alpha_mean = 1, alpha_sd=3)
    fit <- dcon:::fit_decon(y$y, y$D, df = mydf)
    B <- dcon:::construct_basis(y$y, df = mydf)
    df <- data.frame(observed_count = y$y,
                     true_signal = exp(y$B%*%y$a),
                     est_signal = exp(B%*%fit$a))
    #rmse_observed <- sqrt(mean((df$true_signal - df$observed_count)^2))
    #rmse_est <- sqrt(mean((df$true_signal - df$est_signal)^2))
    #c(rmse_observed, rmse_est)
    mad_observed <- median(abs(df$true_signal - df$observed_count))
    mad_est <- median(abs(df$true_signal - df$est_signal))
    c(mad_observed, mad_est)
  }, simplify = 'matrix'))
  if (is.null(all_res)) {
    all_res <- res
  } else {
    all_res <- rbind(all_res, res)
  }
}

as.data.frame(all_res) %>%
  mutate(df = rep(seq(5,20,5),each=B)) %>%
  dplyr::rename(Observed = V1, Deconvolved = V2) %>%
  reshape2::melt(id.vars = 'df') %>%
  filter(variable == 'Deconvolved') %>%
  ggplot(aes(x = factor(df), y = value)) +
  geom_boxplot(outlier.shape=NA) +
  scale_fill_tableau(direction=-1) +
  theme_classic() +
  theme(legend.position = 'none') +
  coord_cartesian(ylim=c(0,200)) +
  xlab('Degrees of freedom') +
  ylab('Median absolute\ndeviation')
ggsave('df-vs-mad-only-est.pdf', height=2.5, width=3)
```



```{r recovering-signal-simulation-gamma}
# Assuming D is correctly specified
# Varying gamma
# fixed length and DF
set.seed(1337)
B <- 10000
LEN <- 20
DF <- 20
true_D <- dcon:::simulate_D(LEN, decay = 1/3, gamma = 1)
all_res <- NULL
for (i in seq(0.1,1,0.3)) {
  mygamma <- i
  res <- t(replicate(B, {
    y <- dcon:::simulate_y(LEN, df = DF, D = true_D, alpha_mean = 1, alpha_sd=3)
    obs_D <- dcon:::simulate_D(LEN, decay = 1/3, gamma = i)
    fit <- dcon:::fit_decon(y$y, obs_D, df = DF)
    B <- dcon:::construct_basis(y$y, df = DF)
    df <- data.frame(observed_count = y$y,
                     true_signal = exp(y$B%*%y$a),
                     est_signal = exp(B%*%fit$a))
    #rmse_observed <- sqrt(mean((df$true_signal - df$observed_count)^2))
    #rmse_est <- sqrt(mean((df$true_signal - df$est_signal)^2))
    #c(rmse_observed, rmse_est)
    mad_observed <- median(abs(df$true_signal - df$observed_count))
    mad_est <- median(abs(df$true_signal - df$est_signal))
    c(mad_observed, mad_est)
  }, simplify = 'matrix'))
  if (is.null(all_res)) {
    all_res <- res
  } else {
    all_res <- rbind(all_res, res)
  }
}

as.data.frame(all_res) %>%
  mutate(gamma = rep(seq(0.1,1,0.3),each=B)) %>%
  dplyr::rename(Observed = V1, Deconvolved = V2) %>%
  reshape2::melt(id.vars = 'gamma') %>%
  filter(variable == 'Deconvolved') %>%
  ggplot(aes(x = factor(gamma), y = value)) +
  geom_boxplot(outlier.shape=NA) +
  scale_fill_tableau(direction=-1) +
  theme_classic() +
  theme(legend.position = 'none') +
  coord_cartesian(ylim=c(0,500)) +
  xlab('Gamma') +
  ylab('Median absolute\ndeviation')
ggsave('gamma-vs-mad-only-est-D-correct.pdf', height=2.5, width=3)
```


```{r}
for (i in 40:50) {
  set.seed(43)
  LEN <- 20
  df <- 20
  true_D <- dcon:::simulate_D(LEN, decay = 1/3)
  obs_D <- true_D
  diag(obs_D) <- diag(obs_D) / 2
  obs_D <- sweep(obs_D, 2, colSums(obs_D),'/')
  y <- dcon:::simulate_y(LEN, df = DF, D = true_D, alpha_mean = -1, alpha_sd=3)
  plot(1:20, y$y)
}

#obs_D <- dcon:::simulate_D(LEN, decay = 1/2, gamma = i, tads=3, tad_strength=1)
fit <- dcon:::fit_decon(y$y, obs_D, df = DF)
B <- dcon:::construct_basis(y$y, df = DF)
df <- data.frame(observed_count = y$y,
                 true_signal = exp(y$B%*%y$a),
                 est_signal = exp(B%*%fit$a))
```



```{r recovering-signal-simulation-gamma}
# Assuming D is incorrectly specified
# Varying gamma
# fixed length and DF
set.seed(43)
N <- 50
LEN <- 20
DF <- 20
true_D <- dcon:::simulate_D(LEN, decay = 1/3)
obs_D <- true_D
diag(obs_D) <- diag(obs_D) / 3
obs_D <- sweep(obs_D, 2, colSums(obs_D),'/')
all_res <- NULL
for (i in seq(0.1,1,0.1)) {
  mygamma <- i
  res <- t(replicate(N, {
    y <- dcon:::simulate_y(LEN, df = DF, D = true_D, npeaks = 1)
    #obs_D <- dcon:::simulate_D(LEN, decay = 1/2, gamma = i, tads=3, tad_strength=1)
    obs_D <- (1-mygamma)*diag(1,nrow=nrow(obs_D))+mygamma*obs_D
    fit <- dcon:::fit_decon(y$y, obs_D, df = DF)
    B <- dcon:::construct_basis(y$y, df = DF)
    df <- data.frame(observed_count = y$y,
                     true_signal = exp(y$B%*%y$a),
                     est_signal = exp(B%*%fit$a))
    rmse_observed <- sqrt(mean((df$true_signal - df$observed_count)^2))
    rmse_est <- sqrt(mean((df$true_signal - df$est_signal)^2))
    c(rmse_observed, rmse_est)
    # mad_observed <- median(abs(df$true_signal - df$observed_count))
    # mad_est <- median(abs(df$true_signal - df$est_signal))
    # c(mad_observed, mad_est)
  }, simplify = 'matrix'))
  if (is.null(all_res)) {
    all_res <- res
  } else {
    all_res <- rbind(all_res, res)
  }
}

as.data.frame(all_res) %>%
  mutate(gamma = rep(seq(0.1,1,0.1),each=N)) %>%
  dplyr::rename(Observed = V1, Deconvolved = V2) %>%
  reshape2::melt(id.vars = 'gamma') %>%
  filter(variable == 'Deconvolved') %>%
  ggplot(aes(x = factor(gamma), y = value)) +
  geom_boxplot() +
  scale_fill_tableau(direction=-1) +
  theme_classic() +
  theme(legend.position = 'none') +
  coord_cartesian(ylim=c(5,15)) +
  xlab('Gamma') +
  ylab('Median absolute\ndeviation')
#ggsave('gamma-vs-mad-only-est-D-misspecified.pdf', height=2.5, width=3)
```


